//! https://bigml.com/api/batchcentroids

use super::{Resource, ResourceCommon};
use super::id::*;
use super::status::*;

/// A batch centroid generated by BigML.
///
/// TODO: Still lots of missing fields.
#[derive(Clone, Debug, Deserialize, Resource, Serialize)]
#[api_name = "batchcentroid"]
pub struct BatchCentroid {
    /// Common resource information. These fields will be serialized at the
    /// top-level of this structure by `serde`.
    #[serde(flatten)]
    pub common: ResourceCommon<BatchCentroid>,

    /// The status of this source.
    pub status: GenericStatus,

    /// Does this centroid include all the fields in the input?
    pub all_fields: bool,

    // Our output dataset.
    //pub output_dataset_resource: Option<Id<Dataset>>,

    /// Is our output dataset currently available?
    pub output_dataset_status: bool,
}

