//! https://bigml.com/api/batchcentroids

use super::Resource;
use super::id::*;
use super::status::*;

resource! {
    api_name "batchcentroid";

    /// A batch centroid generated by BigML.
    ///
    /// TODO: Still lots of missing fields.
    #[derive(Clone, Debug, Deserialize, Serialize)]
    pub struct BatchCentroid {
        /// The status of this source.
        pub status: GenericStatus,

        /// Does this centroid include all the fields in the input?
        pub all_fields: bool,

        // Our output dataset.
        //pub output_dataset_resource: Option<Id<Dataset>>,

        /// Is our output dataset currently available?
        pub output_dataset_status: bool,
    }
}
